### ISSUE TITLE
External IP watch

### ISSUE THREAD

**Issue by nscpro** [compulim/vscode-ipaddress#1]
Hi.

I need external IP watch. Maybe you can take this?

**Comment by compulim** [comment]
Like https://checkip.dyndns.org/?

This is a good idea. But there are some limitations on the status bar, I will implement it as a F1-key function.

**Comment by compulim** [comment]
Your wish is my command.

New version 1.0.0 is released with public IP address queried from OpenDNS via [`check-ip`](https://npmjs.com/package/check-ip).
